export const SEED_FOODS: Array<{
  name: string;
  brand?: string;
  serving_size: number;
  serving_unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  is_verified: boolean;
}> = [
  // ─── Grains & Bread ───────────────────────────────────────────────────────
  {
    name: 'White Rice, Cooked',
    serving_size: 186,
    serving_unit: 'g',
    calories: 242,
    protein: 4.4,
    carbs: 53.4,
    fat: 0.4,
    fiber: 0.6,
    sugar: 0.0,
    sodium: 1.9,
    is_verified: true,
  },
  {
    name: 'Brown Rice, Cooked',
    serving_size: 195,
    serving_unit: 'g',
    calories: 216,
    protein: 5.0,
    carbs: 44.8,
    fat: 1.8,
    fiber: 3.5,
    sugar: 0.7,
    sodium: 9.8,
    is_verified: true,
  },
  {
    name: 'White Bread',
    serving_size: 28,
    serving_unit: 'g',
    calories: 75,
    protein: 2.6,
    carbs: 14.0,
    fat: 1.0,
    fiber: 0.6,
    sugar: 1.4,
    sodium: 142.0,
    is_verified: true,
  },
  {
    name: 'Whole Wheat Bread',
    serving_size: 28,
    serving_unit: 'g',
    calories: 69,
    protein: 3.6,
    carbs: 12.0,
    fat: 1.1,
    fiber: 1.9,
    sugar: 1.4,
    sodium: 132.0,
    is_verified: true,
  },
  {
    name: 'Oatmeal, Cooked',
    serving_size: 234,
    serving_unit: 'g',
    calories: 166,
    protein: 5.9,
    carbs: 28.1,
    fat: 3.6,
    fiber: 4.0,
    sugar: 0.6,
    sodium: 9.4,
    is_verified: true,
  },
  {
    name: 'Pasta, Cooked',
    serving_size: 140,
    serving_unit: 'g',
    calories: 220,
    protein: 8.1,
    carbs: 43.2,
    fat: 1.3,
    fiber: 2.5,
    sugar: 0.6,
    sodium: 1.4,
    is_verified: true,
  },
  {
    name: 'Whole Wheat Pasta, Cooked',
    serving_size: 140,
    serving_unit: 'g',
    calories: 196,
    protein: 8.4,
    carbs: 39.6,
    fat: 1.0,
    fiber: 4.9,
    sugar: 0.7,
    sodium: 2.8,
    is_verified: true,
  },
  {
    name: 'Quinoa, Cooked',
    serving_size: 185,
    serving_unit: 'g',
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fat: 3.6,
    fiber: 5.2,
    sugar: 1.6,
    sodium: 13.0,
    is_verified: true,
  },
  {
    name: 'Bagel, Plain',
    serving_size: 98,
    serving_unit: 'g',
    calories: 270,
    protein: 10.5,
    carbs: 52.1,
    fat: 1.7,
    fiber: 2.3,
    sugar: 5.3,
    sodium: 443.0,
    is_verified: true,
  },
  {
    name: 'Flour Tortilla',
    serving_size: 45,
    serving_unit: 'g',
    calories: 146,
    protein: 3.8,
    carbs: 24.7,
    fat: 3.6,
    fiber: 1.5,
    sugar: 1.1,
    sodium: 217.0,
    is_verified: true,
  },
  {
    name: 'Corn Tortilla',
    serving_size: 26,
    serving_unit: 'g',
    calories: 57,
    protein: 1.5,
    carbs: 11.6,
    fat: 0.7,
    fiber: 1.6,
    sugar: 0.2,
    sodium: 11.0,
    is_verified: true,
  },
  {
    name: 'English Muffin',
    serving_size: 57,
    serving_unit: 'g',
    calories: 134,
    protein: 4.4,
    carbs: 26.2,
    fat: 1.0,
    fiber: 1.5,
    sugar: 2.0,
    sodium: 264.0,
    is_verified: true,
  },
  {
    name: 'Pita Bread',
    serving_size: 60,
    serving_unit: 'g',
    calories: 165,
    protein: 5.5,
    carbs: 33.4,
    fat: 0.7,
    fiber: 1.3,
    sugar: 0.7,
    sodium: 321.0,
    is_verified: true,
  },
  {
    name: 'Cornbread',
    serving_size: 60,
    serving_unit: 'g',
    calories: 173,
    protein: 4.0,
    carbs: 28.3,
    fat: 4.9,
    fiber: 1.4,
    sugar: 7.3,
    sodium: 298.0,
    is_verified: true,
  },
  {
    name: 'Croissant',
    serving_size: 57,
    serving_unit: 'g',
    calories: 231,
    protein: 4.7,
    carbs: 26.1,
    fat: 12.0,
    fiber: 1.5,
    sugar: 5.7,
    sodium: 424.0,
    is_verified: true,
  },
  {
    name: 'Pancake',
    serving_size: 77,
    serving_unit: 'g',
    calories: 175,
    protein: 5.2,
    carbs: 27.8,
    fat: 4.8,
    fiber: 1.0,
    sugar: 5.4,
    sodium: 430.0,
    is_verified: true,
  },
  {
    name: 'Waffle',
    serving_size: 75,
    serving_unit: 'g',
    calories: 218,
    protein: 5.9,
    carbs: 24.7,
    fat: 10.6,
    fiber: 1.3,
    sugar: 4.0,
    sodium: 383.0,
    is_verified: true,
  },
  {
    name: 'Couscous, Cooked',
    serving_size: 157,
    serving_unit: 'g',
    calories: 176,
    protein: 6.0,
    carbs: 36.5,
    fat: 0.3,
    fiber: 2.2,
    sugar: 0.1,
    sodium: 8.0,
    is_verified: true,
  },
  {
    name: 'Rolled Oats, Dry',
    serving_size: 40,
    serving_unit: 'g',
    calories: 154,
    protein: 5.4,
    carbs: 27.8,
    fat: 2.6,
    fiber: 4.0,
    sugar: 0.5,
    sodium: 2.0,
    is_verified: true,
  },
  {
    name: 'Granola',
    serving_size: 49,
    serving_unit: 'g',
    calories: 214,
    protein: 5.5,
    carbs: 37.0,
    fat: 5.0,
    fiber: 3.6,
    sugar: 11.2,
    sodium: 14.0,
    is_verified: true,
  },
  {
    name: 'White Rice, Dry',
    serving_size: 45,
    serving_unit: 'g',
    calories: 162,
    protein: 3.2,
    carbs: 36.0,
    fat: 0.3,
    fiber: 0.5,
    sugar: 0.1,
    sodium: 1.0,
    is_verified: true,
  },
  {
    name: 'Sourdough Bread',
    serving_size: 32,
    serving_unit: 'g',
    calories: 88,
    protein: 3.4,
    carbs: 17.3,
    fat: 0.7,
    fiber: 0.8,
    sugar: 0.8,
    sodium: 185.0,
    is_verified: true,
  },
  {
    name: 'Rye Bread',
    serving_size: 32,
    serving_unit: 'g',
    calories: 83,
    protein: 2.7,
    carbs: 15.5,
    fat: 1.1,
    fiber: 1.9,
    sugar: 1.2,
    sodium: 211.0,
    is_verified: true,
  },
  {
    name: 'Crackers, Whole Wheat',
    serving_size: 28,
    serving_unit: 'g',
    calories: 124,
    protein: 2.5,
    carbs: 19.3,
    fat: 4.6,
    fiber: 2.2,
    sugar: 2.5,
    sodium: 148.0,
    is_verified: true,
  },
  {
    name: 'Muffin, Blueberry',
    serving_size: 113,
    serving_unit: 'g',
    calories: 385,
    protein: 5.4,
    carbs: 62.5,
    fat: 13.5,
    fiber: 1.8,
    sugar: 31.0,
    sodium: 424.0,
    is_verified: true,
  },

  // ─── Proteins / Meat ─────────────────────────────────────────────────────
  {
    name: 'Chicken Breast, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 74.0,
    is_verified: true,
  },
  {
    name: 'Chicken Thigh, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 209,
    protein: 26.0,
    carbs: 0.0,
    fat: 11.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 95.0,
    is_verified: true,
  },
  {
    name: 'Ground Beef 80/20, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 254,
    protein: 26.1,
    carbs: 0.0,
    fat: 17.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 82.0,
    is_verified: true,
  },
  {
    name: 'Ground Beef 93/7, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 175,
    protein: 27.0,
    carbs: 0.0,
    fat: 7.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 79.0,
    is_verified: true,
  },
  {
    name: 'Salmon Fillet, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 208,
    protein: 20.4,
    carbs: 0.0,
    fat: 13.4,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 59.0,
    is_verified: true,
  },
  {
    name: 'Tuna, Canned in Water',
    serving_size: 85,
    serving_unit: 'g',
    calories: 109,
    protein: 20.1,
    carbs: 0.0,
    fat: 2.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 287.0,
    is_verified: true,
  },
  {
    name: 'Egg, Large',
    serving_size: 50,
    serving_unit: 'g',
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 5.0,
    fiber: 0.0,
    sugar: 0.4,
    sodium: 71.0,
    is_verified: true,
  },
  {
    name: 'Egg Whites',
    serving_size: 100,
    serving_unit: 'g',
    calories: 52,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    sugar: 0.7,
    sodium: 166.0,
    is_verified: true,
  },
  {
    name: 'Turkey Breast, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 189,
    protein: 28.6,
    carbs: 0.0,
    fat: 7.4,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 67.0,
    is_verified: true,
  },
  {
    name: 'Pork Chop, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 231,
    protein: 25.7,
    carbs: 0.0,
    fat: 13.8,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 65.0,
    is_verified: true,
  },
  {
    name: 'Shrimp, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 99,
    protein: 18.9,
    carbs: 0.9,
    fat: 1.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 943.0,
    is_verified: true,
  },
  {
    name: 'Tilapia, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 128,
    protein: 26.2,
    carbs: 0.0,
    fat: 2.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 52.0,
    is_verified: true,
  },
  {
    name: 'Cod, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 105,
    protein: 22.8,
    carbs: 0.0,
    fat: 0.9,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 78.0,
    is_verified: true,
  },
  {
    name: 'Steak, Sirloin, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 207,
    protein: 30.7,
    carbs: 0.0,
    fat: 9.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 60.0,
    is_verified: true,
  },
  {
    name: 'Bacon, Pan-Fried',
    serving_size: 15,
    serving_unit: 'g',
    calories: 72,
    protein: 4.7,
    carbs: 0.1,
    fat: 5.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 282.0,
    is_verified: true,
  },
  {
    name: 'Ham, Deli Sliced',
    serving_size: 85,
    serving_unit: 'g',
    calories: 104,
    protein: 14.3,
    carbs: 3.4,
    fat: 3.6,
    fiber: 0.1,
    sugar: 1.9,
    sodium: 1052.0,
    is_verified: true,
  },
  {
    name: 'Sausage, Pork',
    serving_size: 57,
    serving_unit: 'g',
    calories: 198,
    protein: 10.4,
    carbs: 0.6,
    fat: 17.2,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 513.0,
    is_verified: true,
  },
  {
    name: 'Tuna, Canned in Oil',
    serving_size: 85,
    serving_unit: 'g',
    calories: 168,
    protein: 24.8,
    carbs: 0.0,
    fat: 7.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 337.0,
    is_verified: true,
  },
  {
    name: 'Sardines, Canned',
    serving_size: 85,
    serving_unit: 'g',
    calories: 177,
    protein: 21.0,
    carbs: 0.0,
    fat: 9.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 429.0,
    is_verified: true,
  },
  {
    name: 'Ground Turkey, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 203,
    protein: 27.4,
    carbs: 0.0,
    fat: 10.4,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 94.0,
    is_verified: true,
  },
  {
    name: 'Lamb Chop, Cooked',
    serving_size: 100,
    serving_unit: 'g',
    calories: 294,
    protein: 24.5,
    carbs: 0.0,
    fat: 20.9,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 72.0,
    is_verified: true,
  },
  {
    name: 'Chicken Sausage',
    serving_size: 85,
    serving_unit: 'g',
    calories: 162,
    protein: 15.4,
    carbs: 4.6,
    fat: 9.0,
    fiber: 0.0,
    sugar: 1.8,
    sodium: 551.0,
    is_verified: true,
  },
  {
    name: 'Crab, Imitation',
    serving_size: 85,
    serving_unit: 'g',
    calories: 81,
    protein: 6.5,
    carbs: 13.0,
    fat: 0.4,
    fiber: 0.0,
    sugar: 5.0,
    sodium: 715.0,
    is_verified: true,
  },
  {
    name: 'Hot Dog, Beef',
    serving_size: 57,
    serving_unit: 'g',
    calories: 186,
    protein: 6.9,
    carbs: 1.8,
    fat: 16.9,
    fiber: 0.0,
    sugar: 1.0,
    sodium: 521.0,
    is_verified: true,
  },
  {
    name: 'Deli Turkey Breast',
    serving_size: 57,
    serving_unit: 'g',
    calories: 62,
    protein: 12.6,
    carbs: 0.9,
    fat: 0.6,
    fiber: 0.0,
    sugar: 0.6,
    sodium: 592.0,
    is_verified: true,
  },
  {
    name: 'Pepperoni',
    serving_size: 28,
    serving_unit: 'g',
    calories: 138,
    protein: 5.8,
    carbs: 0.5,
    fat: 12.5,
    fiber: 0.0,
    sugar: 0.2,
    sodium: 493.0,
    is_verified: true,
  },
  {
    name: 'Tofu, Firm',
    serving_size: 126,
    serving_unit: 'g',
    calories: 94,
    protein: 10.0,
    carbs: 2.3,
    fat: 5.3,
    fiber: 0.3,
    sugar: 0.6,
    sodium: 9.0,
    is_verified: true,
  },
  {
    name: 'Tempeh',
    serving_size: 84,
    serving_unit: 'g',
    calories: 162,
    protein: 15.4,
    carbs: 7.8,
    fat: 9.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 9.0,
    is_verified: true,
  },
  {
    name: 'Edamame, Shelled',
    serving_size: 100,
    serving_unit: 'g',
    calories: 122,
    protein: 11.9,
    carbs: 8.9,
    fat: 5.2,
    fiber: 5.2,
    sugar: 2.2,
    sodium: 6.0,
    is_verified: true,
  },
  {
    name: 'Seitan',
    serving_size: 85,
    serving_unit: 'g',
    calories: 128,
    protein: 24.5,
    carbs: 4.7,
    fat: 1.5,
    fiber: 0.2,
    sugar: 0.0,
    sodium: 600.0,
    is_verified: true,
  },

  // ─── Dairy ───────────────────────────────────────────────────────────────
  {
    name: 'Whole Milk',
    serving_size: 244,
    serving_unit: 'ml',
    calories: 149,
    protein: 8.0,
    carbs: 11.7,
    fat: 8.0,
    fiber: 0.0,
    sugar: 12.3,
    sodium: 105.0,
    is_verified: true,
  },
  {
    name: '2% Milk',
    serving_size: 244,
    serving_unit: 'ml',
    calories: 122,
    protein: 8.1,
    carbs: 11.7,
    fat: 4.8,
    fiber: 0.0,
    sugar: 12.3,
    sodium: 100.0,
    is_verified: true,
  },
  {
    name: 'Skim Milk',
    serving_size: 244,
    serving_unit: 'ml',
    calories: 83,
    protein: 8.3,
    carbs: 12.2,
    fat: 0.2,
    fiber: 0.0,
    sugar: 12.5,
    sodium: 103.0,
    is_verified: true,
  },
  {
    name: 'Cheddar Cheese',
    serving_size: 28,
    serving_unit: 'g',
    calories: 113,
    protein: 7.0,
    carbs: 0.4,
    fat: 9.3,
    fiber: 0.0,
    sugar: 0.1,
    sodium: 174.0,
    is_verified: true,
  },
  {
    name: 'Greek Yogurt, Plain, Non-fat',
    serving_size: 170,
    serving_unit: 'g',
    calories: 100,
    protein: 17.0,
    carbs: 6.0,
    fat: 0.7,
    fiber: 0.0,
    sugar: 6.0,
    sodium: 65.0,
    is_verified: true,
  },
  {
    name: 'Plain Yogurt, Whole Milk',
    serving_size: 227,
    serving_unit: 'g',
    calories: 149,
    protein: 8.5,
    carbs: 11.4,
    fat: 8.0,
    fiber: 0.0,
    sugar: 11.4,
    sodium: 113.0,
    is_verified: true,
  },
  {
    name: 'Cottage Cheese, 2%',
    serving_size: 113,
    serving_unit: 'g',
    calories: 90,
    protein: 12.0,
    carbs: 4.6,
    fat: 2.5,
    fiber: 0.0,
    sugar: 4.0,
    sodium: 380.0,
    is_verified: true,
  },
  {
    name: 'Butter',
    serving_size: 14,
    serving_unit: 'g',
    calories: 102,
    protein: 0.1,
    carbs: 0.0,
    fat: 11.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 82.0,
    is_verified: true,
  },
  {
    name: 'Cream Cheese',
    serving_size: 28,
    serving_unit: 'g',
    calories: 97,
    protein: 1.7,
    carbs: 1.6,
    fat: 9.7,
    fiber: 0.0,
    sugar: 1.5,
    sodium: 85.0,
    is_verified: true,
  },
  {
    name: 'Mozzarella Cheese',
    serving_size: 28,
    serving_unit: 'g',
    calories: 85,
    protein: 6.3,
    carbs: 0.6,
    fat: 6.3,
    fiber: 0.0,
    sugar: 0.3,
    sodium: 176.0,
    is_verified: true,
  },
  {
    name: 'Parmesan Cheese, Grated',
    serving_size: 5,
    serving_unit: 'g',
    calories: 22,
    protein: 2.0,
    carbs: 0.2,
    fat: 1.4,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 76.0,
    is_verified: true,
  },
  {
    name: 'Heavy Cream',
    serving_size: 15,
    serving_unit: 'ml',
    calories: 52,
    protein: 0.3,
    carbs: 0.4,
    fat: 5.5,
    fiber: 0.0,
    sugar: 0.4,
    sodium: 6.0,
    is_verified: true,
  },
  {
    name: 'Sour Cream',
    serving_size: 30,
    serving_unit: 'g',
    calories: 60,
    protein: 0.9,
    carbs: 1.3,
    fat: 5.8,
    fiber: 0.0,
    sugar: 1.0,
    sodium: 15.0,
    is_verified: true,
  },
  {
    name: 'Swiss Cheese',
    serving_size: 28,
    serving_unit: 'g',
    calories: 108,
    protein: 7.6,
    carbs: 1.5,
    fat: 7.9,
    fiber: 0.0,
    sugar: 0.3,
    sodium: 54.0,
    is_verified: true,
  },
  {
    name: 'Feta Cheese',
    serving_size: 28,
    serving_unit: 'g',
    calories: 75,
    protein: 4.0,
    carbs: 1.2,
    fat: 6.0,
    fiber: 0.0,
    sugar: 1.2,
    sodium: 316.0,
    is_verified: true,
  },
  {
    name: 'Ricotta Cheese, Whole Milk',
    serving_size: 62,
    serving_unit: 'g',
    calories: 108,
    protein: 7.0,
    carbs: 2.0,
    fat: 8.0,
    fiber: 0.0,
    sugar: 0.4,
    sodium: 52.0,
    is_verified: true,
  },
  {
    name: 'Almond Milk, Unsweetened',
    serving_size: 240,
    serving_unit: 'ml',
    calories: 37,
    protein: 1.0,
    carbs: 1.5,
    fat: 2.5,
    fiber: 0.7,
    sugar: 0.0,
    sodium: 150.0,
    is_verified: true,
  },
  {
    name: 'Oat Milk',
    serving_size: 240,
    serving_unit: 'ml',
    calories: 120,
    protein: 3.0,
    carbs: 16.0,
    fat: 5.0,
    fiber: 2.0,
    sugar: 7.0,
    sodium: 101.0,
    is_verified: true,
  },
  {
    name: 'Soy Milk, Unsweetened',
    serving_size: 240,
    serving_unit: 'ml',
    calories: 80,
    protein: 7.0,
    carbs: 4.0,
    fat: 4.0,
    fiber: 1.0,
    sugar: 1.0,
    sodium: 90.0,
    is_verified: true,
  },
  {
    name: 'Whey Protein Powder',
    serving_size: 30,
    serving_unit: 'g',
    calories: 120,
    protein: 24.0,
    carbs: 3.0,
    fat: 1.5,
    fiber: 0.0,
    sugar: 2.0,
    sodium: 130.0,
    is_verified: true,
  },

  // ─── Fruits ──────────────────────────────────────────────────────────────
  {
    name: 'Apple, Medium',
    serving_size: 182,
    serving_unit: 'g',
    calories: 95,
    protein: 0.5,
    carbs: 25.1,
    fat: 0.3,
    fiber: 4.4,
    sugar: 18.9,
    sodium: 1.8,
    is_verified: true,
  },
  {
    name: 'Banana, Medium',
    serving_size: 118,
    serving_unit: 'g',
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    fiber: 3.1,
    sugar: 14.4,
    sodium: 1.2,
    is_verified: true,
  },
  {
    name: 'Orange, Medium',
    serving_size: 131,
    serving_unit: 'g',
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    fiber: 3.1,
    sugar: 12.2,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Strawberries',
    serving_size: 152,
    serving_unit: 'g',
    calories: 49,
    protein: 1.0,
    carbs: 11.7,
    fat: 0.5,
    fiber: 3.0,
    sugar: 7.4,
    sodium: 1.5,
    is_verified: true,
  },
  {
    name: 'Blueberries',
    serving_size: 148,
    serving_unit: 'g',
    calories: 84,
    protein: 1.1,
    carbs: 21.4,
    fat: 0.5,
    fiber: 3.6,
    sugar: 14.7,
    sodium: 1.5,
    is_verified: true,
  },
  {
    name: 'Grapes',
    serving_size: 92,
    serving_unit: 'g',
    calories: 62,
    protein: 0.6,
    carbs: 15.8,
    fat: 0.3,
    fiber: 0.8,
    sugar: 13.7,
    sodium: 1.5,
    is_verified: true,
  },
  {
    name: 'Watermelon',
    serving_size: 280,
    serving_unit: 'g',
    calories: 85,
    protein: 1.7,
    carbs: 21.3,
    fat: 0.4,
    fiber: 1.1,
    sugar: 17.7,
    sodium: 3.4,
    is_verified: true,
  },
  {
    name: 'Pineapple',
    serving_size: 165,
    serving_unit: 'g',
    calories: 82,
    protein: 0.9,
    carbs: 21.6,
    fat: 0.2,
    fiber: 2.3,
    sugar: 16.3,
    sodium: 1.7,
    is_verified: true,
  },
  {
    name: 'Mango',
    serving_size: 165,
    serving_unit: 'g',
    calories: 99,
    protein: 1.4,
    carbs: 24.7,
    fat: 0.6,
    fiber: 2.6,
    sugar: 22.5,
    sodium: 1.7,
    is_verified: true,
  },
  {
    name: 'Peach, Medium',
    serving_size: 150,
    serving_unit: 'g',
    calories: 58,
    protein: 1.4,
    carbs: 14.3,
    fat: 0.4,
    fiber: 2.3,
    sugar: 12.9,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Pear, Medium',
    serving_size: 178,
    serving_unit: 'g',
    calories: 101,
    protein: 0.6,
    carbs: 27.0,
    fat: 0.2,
    fiber: 5.5,
    sugar: 17.4,
    sodium: 1.8,
    is_verified: true,
  },
  {
    name: 'Cherries',
    serving_size: 138,
    serving_unit: 'g',
    calories: 87,
    protein: 1.5,
    carbs: 22.1,
    fat: 0.3,
    fiber: 2.9,
    sugar: 17.7,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Raspberries',
    serving_size: 123,
    serving_unit: 'g',
    calories: 64,
    protein: 1.5,
    carbs: 14.7,
    fat: 0.8,
    fiber: 8.0,
    sugar: 5.4,
    sodium: 1.2,
    is_verified: true,
  },
  {
    name: 'Blackberries',
    serving_size: 144,
    serving_unit: 'g',
    calories: 62,
    protein: 2.0,
    carbs: 13.8,
    fat: 0.7,
    fiber: 7.6,
    sugar: 7.0,
    sodium: 1.4,
    is_verified: true,
  },
  {
    name: 'Kiwi',
    serving_size: 76,
    serving_unit: 'g',
    calories: 46,
    protein: 0.9,
    carbs: 11.1,
    fat: 0.4,
    fiber: 2.3,
    sugar: 6.8,
    sodium: 3.0,
    is_verified: true,
  },
  {
    name: 'Grapefruit, Half',
    serving_size: 123,
    serving_unit: 'g',
    calories: 41,
    protein: 0.8,
    carbs: 10.3,
    fat: 0.1,
    fiber: 1.6,
    sugar: 8.7,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Avocado, Half',
    serving_size: 100,
    serving_unit: 'g',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 7.0,
    is_verified: true,
  },
  {
    name: 'Lemon',
    serving_size: 58,
    serving_unit: 'g',
    calories: 17,
    protein: 0.6,
    carbs: 5.4,
    fat: 0.2,
    fiber: 1.6,
    sugar: 1.5,
    sodium: 1.2,
    is_verified: true,
  },
  {
    name: 'Plum',
    serving_size: 66,
    serving_unit: 'g',
    calories: 30,
    protein: 0.5,
    carbs: 7.5,
    fat: 0.2,
    fiber: 0.9,
    sugar: 6.6,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Cantaloupe',
    serving_size: 177,
    serving_unit: 'g',
    calories: 60,
    protein: 1.5,
    carbs: 14.4,
    fat: 0.3,
    fiber: 1.6,
    sugar: 13.9,
    sodium: 28.0,
    is_verified: true,
  },

  // ─── Vegetables ──────────────────────────────────────────────────────────
  {
    name: 'Broccoli, Raw',
    serving_size: 91,
    serving_unit: 'g',
    calories: 31,
    protein: 2.6,
    carbs: 6.0,
    fat: 0.3,
    fiber: 2.4,
    sugar: 1.5,
    sodium: 30.0,
    is_verified: true,
  },
  {
    name: 'Spinach, Raw',
    serving_size: 30,
    serving_unit: 'g',
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fat: 0.1,
    fiber: 0.7,
    sugar: 0.1,
    sodium: 24.0,
    is_verified: true,
  },
  {
    name: 'Carrots, Raw',
    serving_size: 128,
    serving_unit: 'g',
    calories: 52,
    protein: 1.2,
    carbs: 12.3,
    fat: 0.3,
    fiber: 3.6,
    sugar: 6.1,
    sodium: 88.0,
    is_verified: true,
  },
  {
    name: 'Sweet Potato, Baked',
    serving_size: 114,
    serving_unit: 'g',
    calories: 103,
    protein: 2.3,
    carbs: 23.6,
    fat: 0.1,
    fiber: 3.8,
    sugar: 7.4,
    sodium: 41.0,
    is_verified: true,
  },
  {
    name: 'White Potato, Baked',
    serving_size: 173,
    serving_unit: 'g',
    calories: 161,
    protein: 4.3,
    carbs: 36.6,
    fat: 0.2,
    fiber: 3.8,
    sugar: 1.9,
    sodium: 17.0,
    is_verified: true,
  },
  {
    name: 'Tomato, Medium',
    serving_size: 123,
    serving_unit: 'g',
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fat: 0.2,
    fiber: 1.5,
    sugar: 3.2,
    sodium: 6.0,
    is_verified: true,
  },
  {
    name: 'Cucumber',
    serving_size: 119,
    serving_unit: 'g',
    calories: 16,
    protein: 0.7,
    carbs: 3.8,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.8,
    sodium: 2.4,
    is_verified: true,
  },
  {
    name: 'Bell Pepper, Red',
    serving_size: 119,
    serving_unit: 'g',
    calories: 37,
    protein: 1.2,
    carbs: 7.2,
    fat: 0.4,
    fiber: 2.5,
    sugar: 4.9,
    sodium: 4.8,
    is_verified: true,
  },
  {
    name: 'Bell Pepper, Green',
    serving_size: 119,
    serving_unit: 'g',
    calories: 24,
    protein: 1.0,
    carbs: 5.5,
    fat: 0.2,
    fiber: 2.0,
    sugar: 2.9,
    sodium: 3.6,
    is_verified: true,
  },
  {
    name: 'Onion, Yellow',
    serving_size: 148,
    serving_unit: 'g',
    calories: 60,
    protein: 1.7,
    carbs: 14.0,
    fat: 0.1,
    fiber: 2.7,
    sugar: 6.4,
    sodium: 6.0,
    is_verified: true,
  },
  {
    name: 'Garlic',
    serving_size: 9,
    serving_unit: 'g',
    calories: 13,
    protein: 0.6,
    carbs: 3.0,
    fat: 0.1,
    fiber: 0.2,
    sugar: 0.1,
    sodium: 1.5,
    is_verified: true,
  },
  {
    name: 'Kale, Raw',
    serving_size: 67,
    serving_unit: 'g',
    calories: 34,
    protein: 2.2,
    carbs: 6.7,
    fat: 0.5,
    fiber: 1.3,
    sugar: 1.6,
    sodium: 29.0,
    is_verified: true,
  },
  {
    name: 'Romaine Lettuce',
    serving_size: 85,
    serving_unit: 'g',
    calories: 14,
    protein: 1.2,
    carbs: 2.6,
    fat: 0.2,
    fiber: 1.7,
    sugar: 1.0,
    sodium: 8.5,
    is_verified: true,
  },
  {
    name: 'Corn, Cooked',
    serving_size: 154,
    serving_unit: 'g',
    calories: 177,
    protein: 5.4,
    carbs: 41.2,
    fat: 2.1,
    fiber: 4.6,
    sugar: 9.0,
    sodium: 23.0,
    is_verified: true,
  },
  {
    name: 'Green Peas',
    serving_size: 145,
    serving_unit: 'g',
    calories: 118,
    protein: 7.9,
    carbs: 21.0,
    fat: 0.6,
    fiber: 7.4,
    sugar: 8.2,
    sodium: 7.3,
    is_verified: true,
  },
  {
    name: 'Cauliflower, Raw',
    serving_size: 107,
    serving_unit: 'g',
    calories: 27,
    protein: 2.1,
    carbs: 5.3,
    fat: 0.3,
    fiber: 2.1,
    sugar: 2.4,
    sodium: 32.0,
    is_verified: true,
  },
  {
    name: 'Brussels Sprouts',
    serving_size: 88,
    serving_unit: 'g',
    calories: 38,
    protein: 3.0,
    carbs: 7.9,
    fat: 0.3,
    fiber: 3.3,
    sugar: 1.9,
    sodium: 22.0,
    is_verified: true,
  },
  {
    name: 'Asparagus',
    serving_size: 134,
    serving_unit: 'g',
    calories: 27,
    protein: 3.0,
    carbs: 5.2,
    fat: 0.2,
    fiber: 2.8,
    sugar: 2.5,
    sodium: 2.7,
    is_verified: true,
  },
  {
    name: 'Zucchini',
    serving_size: 124,
    serving_unit: 'g',
    calories: 20,
    protein: 1.5,
    carbs: 4.2,
    fat: 0.4,
    fiber: 1.4,
    sugar: 3.1,
    sodium: 10.0,
    is_verified: true,
  },
  {
    name: 'Celery',
    serving_size: 110,
    serving_unit: 'g',
    calories: 18,
    protein: 0.8,
    carbs: 4.0,
    fat: 0.2,
    fiber: 1.9,
    sugar: 2.0,
    sodium: 86.0,
    is_verified: true,
  },
  {
    name: 'Mushrooms, White',
    serving_size: 96,
    serving_unit: 'g',
    calories: 21,
    protein: 3.0,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1.0,
    sugar: 1.8,
    sodium: 4.8,
    is_verified: true,
  },
  {
    name: 'Beets, Cooked',
    serving_size: 170,
    serving_unit: 'g',
    calories: 74,
    protein: 2.9,
    carbs: 17.0,
    fat: 0.3,
    fiber: 3.4,
    sugar: 12.0,
    sodium: 131.0,
    is_verified: true,
  },
  {
    name: 'Green Beans',
    serving_size: 110,
    serving_unit: 'g',
    calories: 34,
    protein: 2.0,
    carbs: 7.9,
    fat: 0.1,
    fiber: 3.7,
    sugar: 1.6,
    sodium: 6.6,
    is_verified: true,
  },
  {
    name: 'Eggplant',
    serving_size: 99,
    serving_unit: 'g',
    calories: 25,
    protein: 1.0,
    carbs: 5.9,
    fat: 0.2,
    fiber: 3.0,
    sugar: 2.9,
    sodium: 2.0,
    is_verified: true,
  },
  {
    name: 'Butternut Squash',
    serving_size: 140,
    serving_unit: 'g',
    calories: 63,
    protein: 1.4,
    carbs: 16.4,
    fat: 0.1,
    fiber: 2.8,
    sugar: 3.1,
    sodium: 6.0,
    is_verified: true,
  },
  {
    name: 'Artichoke, Cooked',
    serving_size: 120,
    serving_unit: 'g',
    calories: 64,
    protein: 3.5,
    carbs: 14.3,
    fat: 0.4,
    fiber: 6.5,
    sugar: 1.2,
    sodium: 72.0,
    is_verified: true,
  },

  // ─── Legumes & Nuts ──────────────────────────────────────────────────────
  {
    name: 'Black Beans, Cooked',
    serving_size: 172,
    serving_unit: 'g',
    calories: 227,
    protein: 15.2,
    carbs: 40.8,
    fat: 0.9,
    fiber: 15.0,
    sugar: 0.6,
    sodium: 1.7,
    is_verified: true,
  },
  {
    name: 'Chickpeas, Cooked',
    serving_size: 164,
    serving_unit: 'g',
    calories: 269,
    protein: 14.5,
    carbs: 45.0,
    fat: 4.2,
    fiber: 12.5,
    sugar: 7.9,
    sodium: 11.0,
    is_verified: true,
  },
  {
    name: 'Lentils, Cooked',
    serving_size: 198,
    serving_unit: 'g',
    calories: 230,
    protein: 17.9,
    carbs: 39.9,
    fat: 0.8,
    fiber: 15.6,
    sugar: 3.6,
    sodium: 3.6,
    is_verified: true,
  },
  {
    name: 'Kidney Beans, Cooked',
    serving_size: 177,
    serving_unit: 'g',
    calories: 225,
    protein: 15.4,
    carbs: 40.4,
    fat: 0.9,
    fiber: 11.3,
    sugar: 0.6,
    sodium: 3.5,
    is_verified: true,
  },
  {
    name: 'Pinto Beans, Cooked',
    serving_size: 171,
    serving_unit: 'g',
    calories: 245,
    protein: 15.4,
    carbs: 44.8,
    fat: 1.1,
    fiber: 15.4,
    sugar: 0.6,
    sodium: 1.7,
    is_verified: true,
  },
  {
    name: 'Almonds',
    serving_size: 28,
    serving_unit: 'g',
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.2,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 0.3,
    is_verified: true,
  },
  {
    name: 'Peanuts',
    serving_size: 28,
    serving_unit: 'g',
    calories: 161,
    protein: 7.3,
    carbs: 4.6,
    fat: 14.0,
    fiber: 2.4,
    sugar: 1.1,
    sodium: 5.0,
    is_verified: true,
  },
  {
    name: 'Walnuts',
    serving_size: 28,
    serving_unit: 'g',
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fat: 18.5,
    fiber: 1.9,
    sugar: 0.7,
    sodium: 0.6,
    is_verified: true,
  },
  {
    name: 'Cashews',
    serving_size: 28,
    serving_unit: 'g',
    calories: 157,
    protein: 5.2,
    carbs: 8.6,
    fat: 12.4,
    fiber: 0.9,
    sugar: 1.7,
    sodium: 3.4,
    is_verified: true,
  },
  {
    name: 'Peanut Butter, Creamy',
    serving_size: 32,
    serving_unit: 'g',
    calories: 191,
    protein: 7.1,
    carbs: 7.1,
    fat: 16.4,
    fiber: 1.8,
    sugar: 3.4,
    sodium: 136.0,
    is_verified: true,
  },
  {
    name: 'Almond Butter',
    serving_size: 32,
    serving_unit: 'g',
    calories: 196,
    protein: 6.7,
    carbs: 6.1,
    fat: 17.8,
    fiber: 1.7,
    sugar: 1.5,
    sodium: 73.0,
    is_verified: true,
  },
  {
    name: 'Sunflower Seeds',
    serving_size: 28,
    serving_unit: 'g',
    calories: 165,
    protein: 5.5,
    carbs: 7.0,
    fat: 14.0,
    fiber: 2.4,
    sugar: 1.0,
    sodium: 1.1,
    is_verified: true,
  },
  {
    name: 'Pumpkin Seeds',
    serving_size: 28,
    serving_unit: 'g',
    calories: 151,
    protein: 7.0,
    carbs: 5.0,
    fat: 13.0,
    fiber: 1.1,
    sugar: 0.4,
    sodium: 5.3,
    is_verified: true,
  },
  {
    name: 'Chia Seeds',
    serving_size: 28,
    serving_unit: 'g',
    calories: 138,
    protein: 4.7,
    carbs: 11.9,
    fat: 8.7,
    fiber: 9.8,
    sugar: 0.0,
    sodium: 5.3,
    is_verified: true,
  },
  {
    name: 'Flaxseeds',
    serving_size: 10,
    serving_unit: 'g',
    calories: 55,
    protein: 1.9,
    carbs: 3.0,
    fat: 4.3,
    fiber: 2.8,
    sugar: 0.2,
    sodium: 3.1,
    is_verified: true,
  },
  {
    name: 'Hemp Seeds',
    serving_size: 30,
    serving_unit: 'g',
    calories: 166,
    protein: 9.5,
    carbs: 2.6,
    fat: 14.6,
    fiber: 1.2,
    sugar: 0.5,
    sodium: 1.5,
    is_verified: true,
  },
  {
    name: 'Pecans',
    serving_size: 28,
    serving_unit: 'g',
    calories: 196,
    protein: 2.6,
    carbs: 3.9,
    fat: 20.4,
    fiber: 2.7,
    sugar: 1.1,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Pistachios',
    serving_size: 28,
    serving_unit: 'g',
    calories: 159,
    protein: 5.7,
    carbs: 7.7,
    fat: 12.9,
    fiber: 3.0,
    sugar: 2.2,
    sodium: 0.0,
    is_verified: true,
  },
  {
    name: 'Hummus',
    serving_size: 60,
    serving_unit: 'g',
    calories: 106,
    protein: 4.7,
    carbs: 10.2,
    fat: 5.6,
    fiber: 3.4,
    sugar: 0.7,
    sodium: 213.0,
    is_verified: true,
  },

  // ─── Beverages ───────────────────────────────────────────────────────────
  {
    name: 'Orange Juice',
    serving_size: 248,
    serving_unit: 'ml',
    calories: 112,
    protein: 1.7,
    carbs: 25.8,
    fat: 0.5,
    fiber: 0.5,
    sugar: 20.8,
    sodium: 2.5,
    is_verified: true,
  },
  {
    name: 'Apple Juice',
    serving_size: 248,
    serving_unit: 'ml',
    calories: 114,
    protein: 0.2,
    carbs: 28.0,
    fat: 0.3,
    fiber: 0.2,
    sugar: 24.0,
    sodium: 9.9,
    is_verified: true,
  },
  {
    name: 'Coffee, Black',
    serving_size: 237,
    serving_unit: 'ml',
    calories: 2,
    protein: 0.3,
    carbs: 0.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 4.7,
    is_verified: true,
  },
  {
    name: 'Latte, Whole Milk',
    serving_size: 360,
    serving_unit: 'ml',
    calories: 180,
    protein: 10.0,
    carbs: 15.0,
    fat: 7.0,
    fiber: 0.0,
    sugar: 14.0,
    sodium: 140.0,
    is_verified: true,
  },
  {
    name: 'Cola, Regular',
    serving_size: 355,
    serving_unit: 'ml',
    calories: 140,
    protein: 0.0,
    carbs: 39.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 39.0,
    sodium: 45.0,
    is_verified: true,
  },
  {
    name: 'Diet Cola',
    serving_size: 355,
    serving_unit: 'ml',
    calories: 0,
    protein: 0.0,
    carbs: 0.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 40.0,
    is_verified: true,
  },
  {
    name: 'Sports Drink, Gatorade',
    serving_size: 591,
    serving_unit: 'ml',
    calories: 140,
    protein: 0.0,
    carbs: 36.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 34.0,
    sodium: 270.0,
    is_verified: true,
  },
  {
    name: 'Green Tea',
    serving_size: 237,
    serving_unit: 'ml',
    calories: 2,
    protein: 0.2,
    carbs: 0.5,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 2.4,
    is_verified: true,
  },
  {
    name: 'Beer, Regular',
    serving_size: 355,
    serving_unit: 'ml',
    calories: 153,
    protein: 1.6,
    carbs: 12.6,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 14.0,
    is_verified: true,
  },
  {
    name: 'Red Wine',
    serving_size: 148,
    serving_unit: 'ml',
    calories: 125,
    protein: 0.1,
    carbs: 3.8,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.9,
    sodium: 5.9,
    is_verified: true,
  },
  {
    name: 'Whole Milk Cappuccino',
    serving_size: 240,
    serving_unit: 'ml',
    calories: 120,
    protein: 6.0,
    carbs: 10.0,
    fat: 5.0,
    fiber: 0.0,
    sugar: 9.0,
    sodium: 100.0,
    is_verified: true,
  },
  {
    name: 'Coconut Water',
    serving_size: 240,
    serving_unit: 'ml',
    calories: 46,
    protein: 1.7,
    carbs: 8.9,
    fat: 0.5,
    fiber: 2.6,
    sugar: 6.3,
    sodium: 252.0,
    is_verified: true,
  },
  {
    name: 'Grape Juice',
    serving_size: 248,
    serving_unit: 'ml',
    calories: 152,
    protein: 0.9,
    carbs: 37.4,
    fat: 0.2,
    fiber: 0.2,
    sugar: 36.0,
    sodium: 12.0,
    is_verified: true,
  },
  {
    name: 'Almond Milk Latte',
    serving_size: 360,
    serving_unit: 'ml',
    calories: 80,
    protein: 3.0,
    carbs: 11.0,
    fat: 3.0,
    fiber: 0.5,
    sugar: 7.0,
    sodium: 170.0,
    is_verified: true,
  },
  {
    name: 'Protein Shake, Mixed',
    serving_size: 355,
    serving_unit: 'ml',
    calories: 160,
    protein: 25.0,
    carbs: 8.0,
    fat: 3.0,
    fiber: 1.0,
    sugar: 5.0,
    sodium: 200.0,
    is_verified: true,
  },

  // ─── Snacks & Sweets ─────────────────────────────────────────────────────
  {
    name: 'Potato Chips',
    serving_size: 28,
    serving_unit: 'g',
    calories: 152,
    protein: 1.8,
    carbs: 15.2,
    fat: 9.8,
    fiber: 1.2,
    sugar: 0.1,
    sodium: 148.0,
    is_verified: true,
  },
  {
    name: 'Pretzels',
    serving_size: 28,
    serving_unit: 'g',
    calories: 108,
    protein: 2.6,
    carbs: 22.5,
    fat: 0.8,
    fiber: 0.9,
    sugar: 0.9,
    sodium: 386.0,
    is_verified: true,
  },
  {
    name: 'Dark Chocolate, 70%',
    serving_size: 40,
    serving_unit: 'g',
    calories: 216,
    protein: 2.9,
    carbs: 24.0,
    fat: 13.4,
    fiber: 3.1,
    sugar: 17.3,
    sodium: 6.0,
    is_verified: true,
  },
  {
    name: 'Milk Chocolate',
    serving_size: 40,
    serving_unit: 'g',
    calories: 210,
    protein: 2.9,
    carbs: 25.7,
    fat: 11.5,
    fiber: 0.7,
    sugar: 24.0,
    sodium: 28.0,
    is_verified: true,
  },
  {
    name: 'Ice Cream, Vanilla',
    serving_size: 132,
    serving_unit: 'g',
    calories: 273,
    protein: 4.6,
    carbs: 31.2,
    fat: 14.5,
    fiber: 0.5,
    sugar: 28.0,
    sodium: 107.0,
    is_verified: true,
  },
  {
    name: 'Chocolate Chip Cookie',
    serving_size: 16,
    serving_unit: 'g',
    calories: 78,
    protein: 0.9,
    carbs: 10.5,
    fat: 3.7,
    fiber: 0.4,
    sugar: 6.3,
    sodium: 58.0,
    is_verified: true,
  },
  {
    name: 'Granola Bar, Oats & Honey',
    serving_size: 47,
    serving_unit: 'g',
    calories: 193,
    protein: 4.3,
    carbs: 29.0,
    fat: 7.6,
    fiber: 1.7,
    sugar: 12.0,
    sodium: 95.0,
    is_verified: true,
  },
  {
    name: 'Rice Cakes, Plain',
    serving_size: 18,
    serving_unit: 'g',
    calories: 70,
    protein: 1.4,
    carbs: 14.5,
    fat: 0.6,
    fiber: 0.4,
    sugar: 0.0,
    sodium: 30.0,
    is_verified: true,
  },
  {
    name: 'Popcorn, Air-Popped',
    serving_size: 28,
    serving_unit: 'g',
    calories: 108,
    protein: 3.6,
    carbs: 21.8,
    fat: 1.2,
    fiber: 4.2,
    sugar: 0.2,
    sodium: 1.1,
    is_verified: true,
  },
  {
    name: 'Doritos, Nacho Cheese',
    serving_size: 28,
    serving_unit: 'g',
    calories: 140,
    protein: 2.0,
    carbs: 18.0,
    fat: 7.0,
    fiber: 1.0,
    sugar: 1.0,
    sodium: 210.0,
    is_verified: true,
  },
  {
    name: 'Trail Mix',
    serving_size: 43,
    serving_unit: 'g',
    calories: 219,
    protein: 6.0,
    carbs: 22.1,
    fat: 13.1,
    fiber: 2.5,
    sugar: 12.0,
    sodium: 100.0,
    is_verified: true,
  },
  {
    name: 'Brownie',
    serving_size: 56,
    serving_unit: 'g',
    calories: 227,
    protein: 2.7,
    carbs: 35.8,
    fat: 9.1,
    fiber: 1.2,
    sugar: 23.8,
    sodium: 162.0,
    is_verified: true,
  },
  {
    name: 'Donut, Glazed',
    serving_size: 60,
    serving_unit: 'g',
    calories: 253,
    protein: 2.9,
    carbs: 29.3,
    fat: 14.3,
    fiber: 0.7,
    sugar: 15.0,
    sodium: 251.0,
    is_verified: true,
  },
  {
    name: 'Protein Bar',
    serving_size: 60,
    serving_unit: 'g',
    calories: 210,
    protein: 20.0,
    carbs: 23.0,
    fat: 7.0,
    fiber: 3.0,
    sugar: 10.0,
    sodium: 220.0,
    is_verified: true,
  },
  {
    name: 'Gummy Bears',
    serving_size: 45,
    serving_unit: 'g',
    calories: 150,
    protein: 2.0,
    carbs: 36.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 26.0,
    sodium: 25.0,
    is_verified: true,
  },
  {
    name: 'Tortilla Chips',
    serving_size: 28,
    serving_unit: 'g',
    calories: 142,
    protein: 1.9,
    carbs: 19.5,
    fat: 6.7,
    fiber: 1.5,
    sugar: 0.2,
    sodium: 105.0,
    is_verified: true,
  },
  {
    name: 'Cheez-It Crackers',
    serving_size: 30,
    serving_unit: 'g',
    calories: 150,
    protein: 3.0,
    carbs: 19.0,
    fat: 8.0,
    fiber: 0.5,
    sugar: 0.0,
    sodium: 230.0,
    is_verified: true,
  },
  {
    name: 'Peanut Butter Cups',
    serving_size: 42,
    serving_unit: 'g',
    calories: 210,
    protein: 5.0,
    carbs: 25.0,
    fat: 12.0,
    fiber: 1.0,
    sugar: 21.0,
    sodium: 150.0,
    is_verified: true,
  },
  {
    name: 'Jelly Beans',
    serving_size: 40,
    serving_unit: 'g',
    calories: 141,
    protein: 0.0,
    carbs: 36.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 28.0,
    sodium: 13.0,
    is_verified: true,
  },
  {
    name: 'Yogurt Parfait',
    serving_size: 290,
    serving_unit: 'g',
    calories: 357,
    protein: 14.0,
    carbs: 55.0,
    fat: 9.5,
    fiber: 2.5,
    sugar: 32.0,
    sodium: 179.0,
    is_verified: true,
  },

  // ─── Fast Food ───────────────────────────────────────────────────────────
  {
    name: 'Burger Patty, Plain',
    serving_size: 113,
    serving_unit: 'g',
    calories: 287,
    protein: 20.5,
    carbs: 0.0,
    fat: 22.6,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 70.0,
    is_verified: true,
  },
  {
    name: 'French Fries, Medium',
    serving_size: 117,
    serving_unit: 'g',
    calories: 365,
    protein: 4.5,
    carbs: 48.0,
    fat: 17.0,
    fiber: 4.0,
    sugar: 0.4,
    sodium: 400.0,
    is_verified: true,
  },
  {
    name: 'Pizza Slice, Cheese',
    serving_size: 107,
    serving_unit: 'g',
    calories: 285,
    protein: 12.2,
    carbs: 35.7,
    fat: 10.4,
    fiber: 2.3,
    sugar: 3.6,
    sodium: 640.0,
    is_verified: true,
  },
  {
    name: 'Chicken Nuggets, 6 Piece',
    serving_size: 96,
    serving_unit: 'g',
    calories: 271,
    protein: 13.6,
    carbs: 16.5,
    fat: 16.7,
    fiber: 0.7,
    sugar: 0.0,
    sodium: 502.0,
    is_verified: true,
  },
  {
    name: 'Hot Dog with Bun',
    serving_size: 115,
    serving_unit: 'g',
    calories: 311,
    protein: 12.3,
    carbs: 29.3,
    fat: 15.8,
    fiber: 0.8,
    sugar: 5.0,
    sodium: 976.0,
    is_verified: true,
  },
  {
    name: 'Cheeseburger, Fast Food',
    serving_size: 133,
    serving_unit: 'g',
    calories: 354,
    protein: 17.7,
    carbs: 33.6,
    fat: 16.8,
    fiber: 1.0,
    sugar: 7.0,
    sodium: 791.0,
    is_verified: true,
  },
  {
    name: 'Burrito, Bean and Cheese',
    serving_size: 186,
    serving_unit: 'g',
    calories: 378,
    protein: 14.8,
    carbs: 54.8,
    fat: 11.7,
    fiber: 6.2,
    sugar: 2.6,
    sodium: 1043.0,
    is_verified: true,
  },
  {
    name: 'Taco, Beef Crunchy',
    serving_size: 89,
    serving_unit: 'g',
    calories: 210,
    protein: 9.5,
    carbs: 21.0,
    fat: 9.5,
    fiber: 3.0,
    sugar: 1.5,
    sodium: 350.0,
    is_verified: true,
  },
  {
    name: 'Fried Chicken Sandwich',
    serving_size: 200,
    serving_unit: 'g',
    calories: 490,
    protein: 27.0,
    carbs: 47.0,
    fat: 20.0,
    fiber: 2.0,
    sugar: 6.0,
    sodium: 1100.0,
    is_verified: true,
  },
  {
    name: 'Caesar Salad, Fast Food',
    serving_size: 260,
    serving_unit: 'g',
    calories: 300,
    protein: 18.0,
    carbs: 18.0,
    fat: 18.0,
    fiber: 3.0,
    sugar: 4.0,
    sodium: 780.0,
    is_verified: true,
  },
  {
    name: 'Onion Rings, Medium',
    serving_size: 91,
    serving_unit: 'g',
    calories: 276,
    protein: 3.7,
    carbs: 31.3,
    fat: 15.5,
    fiber: 1.7,
    sugar: 3.7,
    sodium: 430.0,
    is_verified: true,
  },
  {
    name: 'Cheese Quesadilla',
    serving_size: 142,
    serving_unit: 'g',
    calories: 442,
    protein: 17.2,
    carbs: 38.9,
    fat: 23.7,
    fiber: 2.5,
    sugar: 1.8,
    sodium: 714.0,
    is_verified: true,
  },
  {
    name: 'Veggie Burger',
    serving_size: 150,
    serving_unit: 'g',
    calories: 289,
    protein: 17.2,
    carbs: 33.0,
    fat: 9.1,
    fiber: 5.5,
    sugar: 5.4,
    sodium: 645.0,
    is_verified: true,
  },
  {
    name: 'Sushi Roll, California',
    serving_size: 170,
    serving_unit: 'g',
    calories: 255,
    protein: 9.0,
    carbs: 38.0,
    fat: 7.0,
    fiber: 3.0,
    sugar: 5.0,
    sodium: 459.0,
    is_verified: true,
  },
  {
    name: 'Pad Thai',
    serving_size: 350,
    serving_unit: 'g',
    calories: 504,
    protein: 21.0,
    carbs: 74.9,
    fat: 14.0,
    fiber: 3.5,
    sugar: 10.5,
    sodium: 1484.0,
    is_verified: true,
  },

  // ─── Condiments & Sauces ─────────────────────────────────────────────────
  {
    name: 'Olive Oil',
    serving_size: 14,
    serving_unit: 'g',
    calories: 119,
    protein: 0.0,
    carbs: 0.0,
    fat: 13.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 0.3,
    is_verified: true,
  },
  {
    name: 'Ketchup',
    serving_size: 17,
    serving_unit: 'g',
    calories: 20,
    protein: 0.3,
    carbs: 5.0,
    fat: 0.0,
    fiber: 0.0,
    sugar: 3.7,
    sodium: 154.0,
    is_verified: true,
  },
  {
    name: 'Mayonnaise',
    serving_size: 14,
    serving_unit: 'g',
    calories: 94,
    protein: 0.1,
    carbs: 0.1,
    fat: 10.4,
    fiber: 0.0,
    sugar: 0.1,
    sodium: 88.0,
    is_verified: true,
  },
  {
    name: 'Mustard, Yellow',
    serving_size: 5,
    serving_unit: 'g',
    calories: 3,
    protein: 0.2,
    carbs: 0.3,
    fat: 0.2,
    fiber: 0.1,
    sugar: 0.1,
    sodium: 56.0,
    is_verified: true,
  },
  {
    name: 'Soy Sauce',
    serving_size: 16,
    serving_unit: 'g',
    calories: 11,
    protein: 1.0,
    carbs: 1.0,
    fat: 0.0,
    fiber: 0.1,
    sugar: 0.4,
    sodium: 902.0,
    is_verified: true,
  },
  {
    name: 'Ranch Dressing',
    serving_size: 30,
    serving_unit: 'g',
    calories: 145,
    protein: 0.5,
    carbs: 1.5,
    fat: 15.5,
    fiber: 0.0,
    sugar: 1.3,
    sodium: 270.0,
    is_verified: true,
  },
  {
    name: 'Salsa',
    serving_size: 62,
    serving_unit: 'g',
    calories: 20,
    protein: 0.8,
    carbs: 4.4,
    fat: 0.2,
    fiber: 1.0,
    sugar: 2.6,
    sodium: 440.0,
    is_verified: true,
  },
  {
    name: 'Guacamole',
    serving_size: 60,
    serving_unit: 'g',
    calories: 97,
    protein: 1.3,
    carbs: 5.6,
    fat: 8.6,
    fiber: 3.9,
    sugar: 0.5,
    sodium: 190.0,
    is_verified: true,
  },
  {
    name: 'Hot Sauce',
    serving_size: 5,
    serving_unit: 'g',
    calories: 1,
    protein: 0.0,
    carbs: 0.1,
    fat: 0.0,
    fiber: 0.0,
    sugar: 0.1,
    sodium: 124.0,
    is_verified: true,
  },
  {
    name: 'Maple Syrup',
    serving_size: 20,
    serving_unit: 'g',
    calories: 52,
    protein: 0.0,
    carbs: 13.4,
    fat: 0.0,
    fiber: 0.0,
    sugar: 12.1,
    sodium: 1.2,
    is_verified: true,
  },
  {
    name: 'Honey',
    serving_size: 21,
    serving_unit: 'g',
    calories: 64,
    protein: 0.1,
    carbs: 17.3,
    fat: 0.0,
    fiber: 0.0,
    sugar: 17.2,
    sodium: 0.8,
    is_verified: true,
  },
  {
    name: 'Balsamic Vinegar',
    serving_size: 15,
    serving_unit: 'g',
    calories: 14,
    protein: 0.1,
    carbs: 2.7,
    fat: 0.0,
    fiber: 0.0,
    sugar: 2.4,
    sodium: 4.4,
    is_verified: true,
  },
];
